return {
PlaceObj('ModItemCharacterDef', {
	Age = 39,
	Bio = T(101971263664, --[[ModItemCharacterDef Janeway Bio]] "BIO Janeway"),
	Equipment = {
		"Jacket_Spaceship",
		"Pants_Spaceship",
		"Shirt_Heavy_Good",
		"Shoes_Heavy",
	},
	Eyes = "Eyes_Krista",
	FavoriteFood = {
		"Coffee",
	},
	FavoriteRelaxation = {
		"PleasureWalk",
		"Reading",
	},
	FirstName = T(923127048072, --[[ModItemCharacterDef Janeway FirstName]] "Kathryn"),
	ForbiddenBreakdowns = {
		"FoodBinge",
		"Bullying",
		"Initial_Crying",
	},
	Hair = "HairFemale1",
	HairColor1 = 4282987044,
	HairColor2 = 4282130446,
	HairMetallic = 127,
	HairParam1 = 60,
	HairParam3 = 133,
	HairParam5 = 190,
	HairRoughness = 21,
	Head = "Head_Katina",
	Headline = T(392507772346, --[[ModItemCharacterDef Janeway Headline]] "Captain"),
	Height = 1720,
	IdealWeight = 65000,
	LastName = T(142292490322, --[[ModItemCharacterDef Janeway LastName]] "Janeway"),
	Payment = 75000000,
	PerceivedGender = "Female",
	Portrait = "Mod/Pmb5Nio/Images/mod_Janeway_small.png",
	PortraitInventory = "UI/Portraits/Inventory/Katina_inventory",
	PortraitLarge = "Mod/Pmb5Nio/Images/mod_Janeway_large.jpg",
	SkillInclinations = {},
	Skills = {
		Combat = 1,
		Intellectual = 1,
		Physical = 1,
	},
	SkinColor = PlaceObj('ColorizationPropSet', {
		'EditableColor1', RGBA(255, 145, 106, 255),
		'EditableColor2', RGBA(255, 107, 72, 255),
		'EditableColor3', RGBA(255, 145, 106, 255),
	}),
	Teeth = "DefaultTeeth_Female",
	Traits = {
		"Calming",
		"FastLearner",
		"Inedia",
	},
	Weight = 62000,
	anim_idle2 = "standing_Idle_Free2_Female",
	anim_idle3 = "standing_Idle_Free3_Female",
	anim_idle4 = "standing_Idle_Free7_Female",
	anim_idle5 = "standing_Idle_Free_Sweat_Female",
	anim_idle6 = "standing_Idle_Free_CleanShoe_Female",
	anim_idle_happy10 = "standing_Idle_Free_CleanShoe_Female",
	anim_idle_happy2 = "standing_Idle_Free2_Female",
	anim_idle_happy3 = "standing_Idle_Free3_Female",
	anim_idle_happy4 = "standing_Idle_Free4_Female",
	anim_idle_happy5 = "standing_Idle_Free5_Female",
	anim_idle_happy6 = "standing_Idle_Free6_Female",
	anim_idle_happy7 = "standing_Idle_Free7_Female",
	anim_idle_happy8 = "standing_Idle_Free_Sweat_Female",
	anim_run = "standing_Walk_Run_Female",
	anim_walk = "standing_Walk_Free_Female",
	anim_walk_distress = "standing_Walk_Distress_Female",
	anim_walk_haste = "standing_Walk_Haste_Female",
	comment = "Kathryn Janeway",
	id = "Janeway",
	save_in = "Mod/Pmb5Nio",
}),
PlaceObj('ModItemCharacterDef', {
	Age = 40,
	Bio = T(857690321941, --[[ModItemCharacterDef Chakotay Bio]] "BIO Chakotay"),
	Equipment = {
		"Jacket_Light_Good",
		"Pants_Spaceship",
		"Shirt_Heavy_Good",
		"Shoes_Heavy",
	},
	FavoriteFood = {
		"StewVegetable",
	},
	FavoriteRelaxation = {
		"PunchingPole",
		"VisitAnimal",
	},
	FirstName = T(478240036639, --[[ModItemCharacterDef Chakotay FirstName]] "Chakotay"),
	ForbiddenBreakdowns = {
		"Stealing",
	},
	Gender = "Male",
	Hair = "Hair_Atticus",
	HairColor1 = 4278848010,
	HairColor2 = 4279308561,
	HairMetallic = 20,
	HairParam3 = 127,
	HairRoughness = 40,
	Head = "Head_Rakha",
	Headline = T(617500786276, --[[ModItemCharacterDef Chakotay Headline]] "Spirit Animal"),
	IdealWeight = 80000,
	LastName = "",
	Payment = 60000000,
	PerceivedGender = "Male",
	Portrait = "Mod/Pmb5Nio/Images/mod_Chakotay_small.jpg",
	PortraitInventory = "UI/Portraits/Inventory/Rakha_inventory",
	PortraitLarge = "Mod/Pmb5Nio/Images/mod_Chakotay_large.jpg",
	SkillInclinations = {
		Construction = "Interested",
	},
	Skills = {
		Combat = 2,
		Construction = 2,
		Crafting = 1,
		Physical = 3,
	},
	SkinColor = PlaceObj('ColorizationPropSet', {
		'EditableColor1', RGBA(160, 106, 85, 255),
		'EditableColor2', RGBA(149, 67, 32, 255),
		'EditableColor3', RGBA(58, 52, 50, 255),
	}),
	Traits = {
		"MasterBuilder",
		"FastWalker",
		"Vegetarian",
		"AnimalTamer",
		"BadMemory",
		"Intimidating",
		"NaturalLeader",
	},
	Weight = 80000,
	anim_idle2 = "standing_Idle_Free2_Female",
	anim_idle3 = "standing_Idle_Free3_Female",
	anim_idle4 = "standing_Idle_Free7_Female",
	anim_idle5 = "standing_Idle_Free_Sweat_Female",
	anim_idle6 = "standing_Idle_Free_CleanShoe_Female",
	anim_idle_happy10 = "standing_Idle_Free_CleanShoe_Female",
	anim_idle_happy2 = "standing_Idle_Free2_Female",
	anim_idle_happy3 = "standing_Idle_Free3_Female",
	anim_idle_happy4 = "standing_Idle_Free4_Female",
	anim_idle_happy5 = "standing_Idle_Free5_Female",
	anim_idle_happy6 = "standing_Idle_Free6_Female",
	anim_idle_happy7 = "standing_Idle_Free7_Female",
	anim_idle_happy8 = "standing_Idle_Free_Sweat_Female",
	anim_run = "standing_Walk_Run",
	anim_walk = "standing_Walk_Free2",
	comment = "Chakotay",
	id = "Chakotay",
	save_in = "Mod/Pmb5Nio",
}),
PlaceObj('ModItemCharacterDef', {
	Age = 33,
	Bio = T(951548185874, --[[ModItemCharacterDef Harry Bio]] "BIO Harry"),
	Equipment = {
		"Shoes_Normal",
		"Shirt_Heavy_Crude",
		"Pants_Spaceship",
	},
	FavoriteFood = {
		"PiePumpkin",
	},
	FavoriteRelaxation = {
		"PlayingArcadeGame",
		"PleasureWalk",
	},
	FirstName = T(389248210530, --[[ModItemCharacterDef Harry FirstName]] "Harry"),
	Gender = "Male",
	Hair = "Hair_Allegra",
	HairColor1 = 4279176975,
	HairColor2 = 4280098077,
	HairParam3 = 127,
	Head = "Head_Quinfan",
	Headline = T(749211970932, --[[ModItemCharacterDef Harry Headline]] "Forever Ensign"),
	Height = 1750,
	IdealWeight = 72000,
	LastName = T(237644823758, --[[ModItemCharacterDef Harry LastName]] "Kim"),
	Payment = 90000000,
	PerceivedGender = "Male",
	Portrait = "Mod/Pmb5Nio/Images/mod_Harry_small.jpg",
	PortraitInventory = "UI/Portraits/Inventory/Quin_inventory",
	PortraitLarge = "Mod/Pmb5Nio/Images/mod_Harry_large 2.jpg",
	SkillInclinations = {
		Crafting = "Interested",
	},
	Skills = {
		Combat = 1,
		Construction = 2,
		Crafting = 1,
		Intellectual = 1,
		Physical = 2,
	},
	SkinColor = PlaceObj('ColorizationPropSet', {
		'EditableColor1', RGBA(198, 120, 73, 255),
		'EditableColor2', RGBA(212, 107, 66, 255),
		'EditableColor3', RGBA(193, 131, 93, 255),
	}),
	Traits = {
		"Explorer",
		"Cheerful",
		"MusicalProdigy",
	},
	Weight = 75000,
	anim_run = "standing_Walk_Run",
	anim_walk = "standing_Walk_Free2",
	comment = "Harry Kim",
	id = "Harry",
	save_in = "Mod/Pmb5Nio",
}),
PlaceObj('ModItemCharacterDef', {
	Age = 35,
	Bio = T(599090417046, --[[ModItemCharacterDef Tom Bio]] "BIO Tom"),
	Equipment = {
		"Shoes_Normal",
		"Shirt_Light_Crude",
		"Pants_Light_Good",
		"Jacket_Spaceship",
	},
	Eyes = "Eyes_Isaac",
	FavoriteFood = {
		"PieMeat",
	},
	FavoriteRelaxation = {
		"WriteShortStory",
		"Reading",
		"TargetPractice",
	},
	FirstName = T(650611424503, --[[ModItemCharacterDef Tom FirstName]] "Tom"),
	Gender = "Male",
	Hair = "Hair_Isaac",
	HairColor1 = 4290879822,
	HairColor2 = 4288112136,
	HairMetallic = 72,
	HairParam2 = 29,
	HairParam3 = 127,
	HairRoughness = 20,
	Head = "Head_Greyson",
	Headline = T(851799427676, --[[ModItemCharacterDef Tom Headline]] "The Pilot"),
	Height = 1780,
	LastName = T(673763419927, --[[ModItemCharacterDef Tom LastName]] "Paris"),
	Payment = 60000000,
	PerceivedGender = "Male",
	Portrait = "Mod/Pmb5Nio/Images/mod_Tom_small.jpg",
	PortraitInventory = "UI/Portraits/Inventory/Simon_inventory",
	PortraitLarge = "Mod/Pmb5Nio/Images/mod_Tom_large.jpg",
	SkillInclinations = {
		Construction = "Interested",
		Cooking = "Forbidden",
		Farming = "Indifferent",
		Physical = "Interested",
	},
	Skills = {
		Combat = 2,
		Construction = 2,
		Physical = 4,
	},
	SkinColor = PlaceObj('ColorizationPropSet', {
		'EditableColor1', RGBA(255, 138, 92, 255),
		'EditableColor2', RGBA(254, 109, 75, 255),
		'EditableColor3', RGBA(255, 138, 92, 255),
	}),
	Traits = {
		"EntertainmentJunkie",
		"InspirationalWriter",
		"CoagulatedBlood",
	},
	anim_idle2 = "standing_Idle_Free2_Female",
	anim_idle3 = "standing_Idle_Free3_Female",
	anim_idle_happy2 = "standing_Idle_Free2_Female",
	anim_idle_happy3 = "standing_Idle_Free3_Female",
	anim_idle_happy4 = "standing_Idle_Free4_Female",
	anim_idle_happy5 = "standing_Idle_Free5_Female",
	anim_run = "standing_Walk_Run",
	anim_walk = "standing_Walk_Free2",
	comment = "Tom Paris",
	id = "Tom",
	save_in = "Mod/Pmb5Nio",
}),
PlaceObj('ModItemCharacterDef', {
	Age = 41,
	Bio = T(737690526422, --[[ModItemCharacterDef Tuvok Bio]] "BIO Tuvok"),
	Equipment = {
		"Pants_Spaceship",
		"Jacket_Spaceship",
		"Shoes_Heavy",
	},
	FavoriteFood = {
		"HaySausage",
		"Earplugs",
	},
	FavoriteRelaxation = {
		"SittingArmchair",
		"Praying",
	},
	FirstName = T(607031609618, --[[ModItemCharacterDef Tuvok FirstName]] "Tuvok"),
	ForbiddenBreakdowns = {
		"Initial_Crying",
		"DrinkingBinge",
		"FoodBinge",
	},
	Gender = "Male",
	Hair = "Hair_Omar",
	HairColor1 = 4279045389,
	HairColor2 = 4279045389,
	HairColor3 = 4279045389,
	HairParam3 = 127,
	Head = "Head_Umayr",
	Headline = T(744626527428, --[[ModItemCharacterDef Tuvok Headline]] "It's only logical"),
	LastName = "",
	Payment = 45000000,
	PerceivedGender = "Male",
	Portrait = "Mod/Pmb5Nio/Images/mod_Tuvok_small.jpg",
	PortraitInventory = "UI/Portraits/Inventory/Umayr_inventory",
	PortraitLarge = "Mod/Pmb5Nio/Images/mod_Tuvok_large.jpg",
	SkillInclinations = {
		Cooking = "Forbidden",
		Farming = "Indifferent",
		Intellectual = "Interested",
	},
	Skills = {
		Combat = 3,
		Construction = 1,
		Crafting = 1,
		Intellectual = 5,
		Physical = 4,
	},
	SkinColor = PlaceObj('ColorizationPropSet', {
		'EditableColor1', RGBA(103, 40, 21, 255),
		'EditableColor2', RGBA(151, 75, 42, 255),
		'EditableColor3', RGBA(75, 55, 45, 255),
	}),
	Traits = {
		"Liberated",
		"TacticalCommander",
		"Healthy",
	},
	anim_run = "standing_Walk_Run",
	anim_walk = "standing_Walk_Free2",
	comment = "Tuvok",
	id = "Tuvok",
	save_in = "Mod/Pmb5Nio",
}),
PlaceObj('ModItemCharacterDef', {
	Age = 41,
	Beard = "Beard_Russell",
	Bio = T(190223829656, --[[ModItemCharacterDef Neelix Bio]] "BIO Neelix"),
	Equipment = {
		"AncientTalisman",
		"Shirt_Heavy_Crude",
		"Shoes_Normal",
		"Pants_Spaceship",
	},
	Eyes = "Eyes_Vicente",
	FavoriteFood = {
		"MushroomCroquettes",
	},
	FavoriteRelaxation = {
		"AppreciatingDecoration",
		"Drinking",
	},
	FirstName = T(563740202579, --[[ModItemCharacterDef Neelix FirstName]] "Neelix"),
	Gender = "Male",
	Hair = "Hair_Vicente",
	HairColor1 = 4291983642,
	HairColor2 = 4289816086,
	HairColor3 = 4288302620,
	HairMetallic = -128,
	HairParam3 = 127,
	HairRoughness = 31,
	Head = "Head_Delano",
	Headline = T(137345522968, --[[ModItemCharacterDef Neelix Headline]] "Chef, Morale Officer, Ambassador and Negotiator"),
	Height = 1650,
	LastName = "",
	Payment = 60000000,
	PerceivedGender = "Male",
	Portrait = "Mod/Pmb5Nio/Images/mod_Neelix_small.jpg",
	PortraitInventory = "UI/Portraits/Inventory/Connor_inventory",
	PortraitLarge = "Mod/Pmb5Nio/Images/mod_Neelix_large.jpg",
	SkillInclinations = {
		Combat = "Indifferent",
		Cooking = "Interested",
		Farming = "Interested",
		Intellectual = "Indifferent",
	},
	Skills = {
		Cooking = 5,
		Farming = 5,
	},
	SkinColor = PlaceObj('ColorizationPropSet', {
		'EditableColor1', RGBA(176, 121, 43, 255),
		'EditableColor2', RGBA(254, 109, 75, 255),
		'EditableColor3', RGBA(255, 138, 92, 255),
	}),
	Teeth = "Teeth_Vicente",
	Traits = {
		"ExcquisiteCook",
		"Cheerful",
		"Glutton",
		"AvidFarmer",
		"Haggler",
		"Sickly",
		"Sleepy",
	},
	Weight = 90000,
	anim_run = "standing_Walk_Run",
	anim_walk = "standing_Walk_Free2",
	comment = "Neelix",
	id = "Neelix",
	save_in = "Mod/Pmb5Nio",
}),
PlaceObj('ModItemCharacterDef', {
	Age = 39,
	Bio = T(487913187171, --[[ModItemCharacterDef Belanna Bio]] "BIO B'Elanna"),
	Equipment = {
		"Armor_Shoes_Carbon",
		"Armor_Jacket_Carbon",
		"Armor_Pants_Carbon",
	},
	Eyes = "Eyes_Gabriele",
	FatiguePerDay = 55000,
	FavoriteRelaxation = {
		"Drinking",
		"PunchingPole",
		"TargetPractice",
	},
	FirstName = T(649576326681, --[[ModItemCharacterDef Belanna FirstName]] "B'Elanna"),
	Hair = "HairFemale4",
	HairColor1 = 4278584581,
	HairColor2 = 4279176975,
	HairMetallic = -77,
	HairParam1 = 89,
	HairParam2 = 35,
	HairParam3 = 127,
	Head = "Head_Vanessa",
	Headline = T(423560975078, --[[ModItemCharacterDef Belanna Headline]] "Chief Engineer"),
	Height = 1600,
	IdealWeight = 60000,
	LastName = T(597845332588, --[[ModItemCharacterDef Belanna LastName]] "Torres"),
	Payment = 45000000,
	PerceivedGender = "Female",
	Portrait = "Mod/Pmb5Nio/Images/mod_BElanna_small.jpg",
	PortraitInventory = "UI/Portraits/Inventory/Vanessa_inventory",
	PortraitLarge = "Mod/Pmb5Nio/Images/mod_BElanna_large.jpg",
	SkillInclinations = {
		Combat = "Interested",
		Farming = "Indifferent",
		Healing = "Indifferent",
	},
	Skills = {
		Combat = 3,
		Construction = 1,
		Crafting = 1,
		Physical = 4,
	},
	SkinColor = PlaceObj('ColorizationPropSet', {
		'EditableColor1', RGBA(162, 97, 59, 255),
		'EditableColor2', RGBA(162, 107, 54, 255),
		'EditableColor3', RGBA(131, 69, 55, 255),
	}),
	Teeth = "Teeth_Gabriele",
	TemperatureHigh = 42000,
	TemperatureLow = 12000,
	Traits = {
		"Engineer",
		"CombatInstructor",
		"Bloodlust",
		"Glutton",
	},
	Weight = 60000,
	anim_idle2 = "standing_Idle_Free2_Female",
	anim_idle3 = "standing_Idle_Free3_Female",
	anim_idle4 = "standing_Idle_Free7_Female",
	anim_idle5 = "standing_Idle_Free_Sweat_Female",
	anim_idle6 = "standing_Idle_Free_CleanShoe_Female",
	anim_idle_happy10 = "standing_Idle_Free_CleanShoe_Female",
	anim_idle_happy2 = "standing_Idle_Free2_Female",
	anim_idle_happy3 = "standing_Idle_Free3_Female",
	anim_idle_happy4 = "standing_Idle_Free4_Female",
	anim_idle_happy5 = "standing_Idle_Free5_Female",
	anim_idle_happy6 = "standing_Idle_Free6_Female",
	anim_idle_happy7 = "standing_Idle_Free7_Female",
	anim_idle_happy8 = "standing_Idle_Free_Sweat_Female",
	anim_run = "standing_Walk_Run_Female",
	anim_walk = "standing_Walk_Free2_Female",
	anim_walk_distress = "standing_Walk_Distress_Female",
	anim_walk_haste = "standing_Walk_Haste_Female",
	comment = "B'Elanna Torres",
	id = "Belanna",
	save_in = "Mod/Pmb5Nio",
}),
}
