return {
PlaceObj('ModItemCharacterDef', {
	Age = 39,
	Bio = T(221059469465, --[[ModItemCharacterDef Janeway Bio]] "Kathryn Janeway is a clever and resilient leader recognized for her strategic thinking, known for her unwavering determination and excels at making tough decisions.\nBeing experienced in managing complex situations, guiding her team through unfamiliar and challenging environments, while also navigating moral dilemmas.\nHer ability to learn and adapt quickly and maintain focus under pressure helps her being an effective and innovative leader capable of guiding her crew through the most challenging situations and keep going even when things get rough."),
	Equipment = {
		"Jacket_Spaceship",
		"Pants_Spaceship",
		"Shirt_Heavy_Good",
		"Shoes_Heavy",
	},
	Eyes = "Eyes_Krista",
	FavoriteFood = {
		"Coffee",
	},
	FavoriteRelaxation = {
		"Reading",
	},
	FirstName = T(540606911077, --[[ModItemCharacterDef Janeway FirstName]] "Kathryn"),
	ForbiddenBreakdowns = {
		"FoodBinge",
		"Bullying",
		"Initial_Crying",
		"Berserk",
		"Catatonia",
		"Crying",
		"DrinkingBinge",
		"Hiding",
		"SadWalk",
		"Stealing",
	},
	Hair = "HairFemale1",
	HairColor1 = 4282987044,
	HairColor2 = 4282130446,
	HairMetallic = 127,
	HairParam1 = 60,
	HairParam3 = 133,
	HairParam5 = 190,
	HairRoughness = 21,
	Head = "Head_Katina",
	Headline = T(839242343075, --[[ModItemCharacterDef Janeway Headline]] "Captain"),
	Height = 1720,
	IdealWeight = 65000,
	LastName = T(826657576370, --[[ModItemCharacterDef Janeway LastName]] "Janeway"),
	Payment = 75000000,
	PerceivedGender = "Female",
	Portrait = "Mod/Pmb5Nio/Images/mod_Janeway_small.png",
	PortraitInventory = "UI/Portraits/Inventory/Katina_inventory",
	PortraitLarge = "Mod/Pmb5Nio/Images/mod_Janeway_large.jpg",
	SkillInclinations = {},
	Skills = {
		Combat = 1,
		Intellectual = 1,
		Physical = 1,
	},
	SkinColor = PlaceObj('ColorizationPropSet', {
		'EditableColor1', RGBA(255, 145, 106, 255),
		'EditableColor2', RGBA(255, 107, 72, 255),
		'EditableColor3', RGBA(255, 145, 106, 255),
	}),
	Teeth = "DefaultTeeth_Female",
	Traits = {
		"Calming",
		"FastLearner",
		"Inedia",
	},
	Weight = 62000,
	anim_idle2 = "standing_Idle_Free2_Female",
	anim_idle3 = "standing_Idle_Free3_Female",
	anim_idle4 = "standing_Idle_Free7_Female",
	anim_idle5 = "standing_Idle_Free_Sweat_Female",
	anim_idle6 = "standing_Idle_Free_CleanShoe_Female",
	anim_idle_happy10 = "standing_Idle_Free_CleanShoe_Female",
	anim_idle_happy2 = "standing_Idle_Free2_Female",
	anim_idle_happy3 = "standing_Idle_Free3_Female",
	anim_idle_happy4 = "standing_Idle_Free4_Female",
	anim_idle_happy5 = "standing_Idle_Free5_Female",
	anim_idle_happy6 = "standing_Idle_Free6_Female",
	anim_idle_happy7 = "standing_Idle_Free7_Female",
	anim_idle_happy8 = "standing_Idle_Free_Sweat_Female",
	anim_run = "standing_Walk_Run_Female",
	anim_walk = "standing_Walk_Free_Female",
	anim_walk_distress = "standing_Walk_Distress_Female",
	anim_walk_haste = "standing_Walk_Haste_Female",
	comment = "Kathryn Janeway",
	id = "Janeway",
	save_in = "Mod/Pmb5Nio",
}),
PlaceObj('ModItemCharacterDef', {
	Age = 40,
	Bio = T(150460911192, --[[ModItemCharacterDef Chakotay Bio]] "Commander Chakotay is a calm, steadfast leader with sharp strategic insight and strong technical skills. He excels at analyzing complex situations, fostering teamwork, and adapting to changing circumstances. His practical mindset, cultural awareness, and steady presence help maintain morale and unity, making him a reliable and resourceful first officer in any situation."),
	Equipment = {
		"Jacket_Light_Good",
		"Pants_Spaceship",
		"Shirt_Heavy_Good",
		"Shoes_Heavy",
	},
	FavoriteFood = {
		"StewVegetable",
	},
	FavoriteRelaxation = {
		"PunchingPole",
		"VisitAnimal",
	},
	FirstName = T(796170828780, --[[ModItemCharacterDef Chakotay FirstName]] "Chakotay"),
	ForbiddenBreakdowns = {
		"Stealing",
		"Hiding",
		"Initial_Crying",
	},
	Gender = "Male",
	Hair = "Hair_Atticus",
	HairColor1 = 4278848010,
	HairColor2 = 4279308561,
	HairMetallic = 20,
	HairParam3 = 127,
	HairRoughness = 40,
	Head = "Head_Rakha",
	Headline = T(145792514938, --[[ModItemCharacterDef Chakotay Headline]] "Spirit Animal"),
	IdealWeight = 80000,
	KnownTechs = {
		"AnimalTaming",
	},
	LastName = "",
	Payment = 60000000,
	PerceivedGender = "Male",
	Portrait = "Mod/Pmb5Nio/Images/mod_Chakotay_small.jpg",
	PortraitInventory = "UI/Portraits/Inventory/Rakha_inventory",
	PortraitLarge = "Mod/Pmb5Nio/Images/mod_Chakotay_large.jpg",
	SkillInclinations = {
		Construction = "Interested",
	},
	Skills = {
		Combat = 2,
		Construction = 2,
		Crafting = 1,
		Physical = 3,
	},
	SkinColor = PlaceObj('ColorizationPropSet', {
		'EditableColor1', RGBA(160, 106, 85, 255),
		'EditableColor2', RGBA(149, 67, 32, 255),
		'EditableColor3', RGBA(58, 52, 50, 255),
	}),
	Traits = {
		"MasterBuilder",
		"FastWalker",
		"Vegetarian",
		"AnimalTamer",
		"BadMemory",
		"Intimidating",
		"NaturalLeader",
		"AvidCarpenter",
	},
	Weight = 80000,
	anim_idle2 = "standing_Idle_Free2_Female",
	anim_idle3 = "standing_Idle_Free3_Female",
	anim_idle4 = "standing_Idle_Free7_Female",
	anim_idle5 = "standing_Idle_Free_Sweat_Female",
	anim_idle6 = "standing_Idle_Free_CleanShoe_Female",
	anim_idle_happy10 = "standing_Idle_Free_CleanShoe_Female",
	anim_idle_happy2 = "standing_Idle_Free2_Female",
	anim_idle_happy3 = "standing_Idle_Free3_Female",
	anim_idle_happy4 = "standing_Idle_Free4_Female",
	anim_idle_happy5 = "standing_Idle_Free5_Female",
	anim_idle_happy6 = "standing_Idle_Free6_Female",
	anim_idle_happy7 = "standing_Idle_Free7_Female",
	anim_idle_happy8 = "standing_Idle_Free_Sweat_Female",
	anim_run = "standing_Walk_Run",
	anim_walk = "standing_Walk_Free2",
	comment = "Chakotay",
	id = "Chakotay",
	save_in = "Mod/Pmb5Nio",
}),
PlaceObj('ModItemCharacterDef', {
	Age = 33,
	Bio = T(571483443554, --[[ModItemCharacterDef Harry Bio]] "Harry Kim is a bright and dedicated operations officer recognized for his quick learning, technical expertise, and composure under pressure. His curiosity and adaptability allow him to master new systems rapidly and respond effectively to unexpected challenges. With a strong sense of duty and a genuine commitment to excellence, Kim consistently supports his crew through precision, teamwork, and optimism. His enthusiasm, intelligence, and reliability make him an invaluable member of any mission."),
	Equipment = {
		"Shoes_Normal",
		"Shirt_Heavy_Crude",
		"Pants_Spaceship",
	},
	FavoriteFood = {
		"PiePumpkin",
	},
	FavoriteRelaxation = {
		"PlayingArcadeGame",
	},
	FirstName = T(308371987979, --[[ModItemCharacterDef Harry FirstName]] "Harry"),
	Gender = "Male",
	Hair = "Hair_Allegra",
	HairColor1 = 4279176975,
	HairColor2 = 4280098077,
	HairParam3 = 127,
	Head = "Head_Quinfan",
	Headline = T(450905854309, --[[ModItemCharacterDef Harry Headline]] "Forever Ensign"),
	Height = 1750,
	IdealWeight = 72000,
	LastName = T(278764211858, --[[ModItemCharacterDef Harry LastName]] "Kim"),
	Payment = 90000000,
	PerceivedGender = "Male",
	Portrait = "Mod/Pmb5Nio/Images/mod_Harry_small.jpg",
	PortraitInventory = "UI/Portraits/Inventory/Quin_inventory",
	PortraitLarge = "Mod/Pmb5Nio/Images/mod_Harry_large 2.jpg",
	SkillInclinations = {
		Crafting = "Interested",
	},
	Skills = {
		Combat = 1,
		Construction = 1,
		Crafting = 1,
		Intellectual = 1,
		Physical = 2,
	},
	SkinColor = PlaceObj('ColorizationPropSet', {
		'EditableColor1', RGBA(198, 120, 73, 255),
		'EditableColor2', RGBA(212, 107, 66, 255),
		'EditableColor3', RGBA(193, 131, 93, 255),
	}),
	Traits = {
		"Explorer",
		"NaturalCuriosity",
		"MusicalProdigy",
		"AvidTailor",
	},
	Weight = 75000,
	anim_run = "standing_Walk_Run",
	anim_walk = "standing_Walk_Free2",
	comment = "Harry Kim",
	id = "Harry",
	save_in = "Mod/Pmb5Nio",
}),
PlaceObj('ModItemCharacterDef', {
	Age = 35,
	Bio = T(100153135456, --[[ModItemCharacterDef Tom Bio]] "Tom Paris is a talented, inventive pilot whose creative problem-solving skills allow him to navigate complex challenges and often lead to innovative solutions that get everyone out of tricky spots. His adventurous spirit fuels his technical expertise. He likes to write Holodeck simulations like Captain Proton, Fair Haven and enjoys classic movies. Being stranded now, options are limited but he's keen to find out new ways keeping him and the crew entertained."),
	Equipment = {
		"Shoes_Normal",
		"Shirt_Light_Crude",
		"Pants_Light_Good",
		"Jacket_Spaceship",
	},
	Eyes = "Eyes_Isaac",
	FavoriteFood = {
		"PizzaVegetable",
	},
	FavoriteRelaxation = {
		"WriteShortStory",
		"Reading",
		"TargetPractice",
	},
	FirstName = T(116253615634, --[[ModItemCharacterDef Tom FirstName]] "Tom"),
	Gender = "Male",
	Hair = "Hair_Isaac",
	HairColor1 = 4290879822,
	HairColor2 = 4288112136,
	HairMetallic = 72,
	HairParam2 = 29,
	HairParam3 = 127,
	HairRoughness = 20,
	Head = "Head_Greyson",
	Headline = T(485334664904, --[[ModItemCharacterDef Tom Headline]] "The Pilot"),
	Height = 1790,
	LastName = T(519475057606, --[[ModItemCharacterDef Tom LastName]] "Paris"),
	Payment = 60000000,
	PerceivedGender = "Male",
	Portrait = "Mod/Pmb5Nio/Images/mod_Tom_small.jpg",
	PortraitInventory = "UI/Portraits/Inventory/Simon_inventory",
	PortraitLarge = "Mod/Pmb5Nio/Images/mod_Tom_large.jpg",
	SkillInclinations = {
		Construction = "Interested",
		Cooking = "Forbidden",
		Farming = "Indifferent",
		Healing = "Interested",
		Physical = "Interested",
	},
	Skills = {
		Combat = 2,
		Construction = 2,
		Healing = 1,
		Physical = 4,
	},
	SkinColor = PlaceObj('ColorizationPropSet', {
		'EditableColor1', RGBA(255, 138, 92, 255),
		'EditableColor2', RGBA(254, 109, 75, 255),
		'EditableColor3', RGBA(255, 138, 92, 255),
	}),
	Traits = {
		"EntertainmentJunkie",
		"InspirationalWriter",
		"CoagulatedBlood",
		"ExperiencedScavenger",
	},
	anim_idle2 = "standing_Idle_Free2_Female",
	anim_idle3 = "standing_Idle_Free3_Female",
	anim_idle_happy2 = "standing_Idle_Free2_Female",
	anim_idle_happy3 = "standing_Idle_Free3_Female",
	anim_idle_happy4 = "standing_Idle_Free4_Female",
	anim_idle_happy5 = "standing_Idle_Free5_Female",
	anim_run = "standing_Walk_Run",
	anim_walk = "standing_Walk_Free2",
	comment = "Tom Paris",
	id = "Tom",
	save_in = "Mod/Pmb5Nio",
}),
PlaceObj('ModItemCharacterDef', {
	Age = 41,
	Bio = T(136409015869, --[[ModItemCharacterDef Tuvok Bio]] "Tuvok is a disciplined and logical Vulcan security officer with deep expertise in tactics, strategy, and mental discipline. His calm focus and analytical precision bring stability in crises, while his professionalism and composure ensure the crew's safety and order. Reliable, intelligent, and efficient, Tuvok embodies the ideal balance of logic and leadership."),
	Equipment = {
		"Pants_Spaceship",
		"Jacket_Spaceship",
		"Shoes_Heavy",
	},
	FatiguePerDay = 55000,
	FavoriteFood = {
		"HaySausage",
	},
	FavoriteRelaxation = {
		"SittingArmchair",
		"Praying",
	},
	FirstName = T(196242859330, --[[ModItemCharacterDef Tuvok FirstName]] "Tuvok"),
	Gender = "Male",
	Hair = "Hair_Omar",
	HairColor1 = 4279045389,
	HairColor2 = 4279045389,
	HairColor3 = 4279045389,
	HairParam3 = 127,
	Head = "Head_Umayr",
	Headline = T(611537761014, --[[ModItemCharacterDef Tuvok Headline]] "It's only logical"),
	Height = 1900,
	LastName = "",
	Payment = 45000000,
	PerceivedGender = "Male",
	Portrait = "Mod/Pmb5Nio/Images/mod_Tuvok_small.jpg",
	PortraitInventory = "UI/Portraits/Inventory/Umayr_inventory",
	PortraitLarge = "Mod/Pmb5Nio/Images/mod_Tuvok_large.jpg",
	SkillInclinations = {
		Cooking = "Forbidden",
		Farming = "Indifferent",
		Intellectual = "Interested",
	},
	Skills = {
		Combat = 3,
		Crafting = 1,
		Intellectual = 5,
		Physical = 4,
	},
	SkinColor = PlaceObj('ColorizationPropSet', {
		'EditableColor1', RGBA(103, 40, 21, 255),
		'EditableColor2', RGBA(151, 75, 42, 255),
		'EditableColor3', RGBA(75, 55, 45, 255),
	}),
	TemperatureHigh = 42000,
	Traits = {
		"Liberated",
		"TacticalCommander",
		"Healthy",
		"Genius",
		"Vegetarian",
	},
	anim_run = "standing_Walk_Run",
	anim_walk = "standing_Walk_Free2",
	comment = "Tuvok",
	id = "Tuvok",
	save_in = "Mod/Pmb5Nio",
}),
PlaceObj('ModItemCharacterDef', {
	Age = 41,
	Beard = "Beard_Russell",
	Bio = T(456606679201, --[[ModItemCharacterDef Neelix Bio]] "Neelix is a cheerful Talaxian, seeing himself as morale officer who lifts spirits with his positive attitude and practical solutions. His warmth helps create a strong sense of community even during tough times.\nHe is known for his culinary skills, positive attitude and he excels in cooking, hospitality, and cultural exchange.\nHist background includes navigating unfamiliar environments, improvising solutions with limited resources and maintaining optimism in challenging circumstances.\nHis interpersonal skills, adaptability and deep empathy make him an invaluable team member, fostering camaraderie and ensuring the well-being of his colleagues on long voyages.\n"),
	Equipment = {
		"AncientTalisman",
		"Shirt_Heavy_Crude",
		"Shoes_Normal",
		"Pants_Spaceship",
	},
	Eyes = "Eyes_Delano",
	FavoriteFood = {
		"MushroomCroquettes",
	},
	FavoriteRelaxation = {
		"AppreciatingDecoration",
		"Drinking",
		"Reading",
	},
	FirstName = T(802065302630, --[[ModItemCharacterDef Neelix FirstName]] "Neelix"),
	ForbiddenBreakdowns = {
		"Berserk",
		"Bullying",
	},
	Gender = "Male",
	Hair = "Hair_Vicente",
	HairColor1 = 4291983642,
	HairColor2 = 4289816086,
	HairColor3 = 4288302620,
	HairMetallic = -128,
	HairParam3 = 127,
	HairRoughness = 31,
	Head = "Head_Delano",
	Headline = T(735188509127, --[[ModItemCharacterDef Neelix Headline]] "Chef, Morale Officer, Ambassador and Negotiator"),
	Height = 1650,
	KnownTechs = {
		"HaySausage",
		"LiquidFuelFromInsectMeat",
	},
	LastName = "",
	Payment = 60000000,
	PerceivedGender = "Male",
	Portrait = "Mod/Pmb5Nio/Images/mod_Neelix_small.jpg",
	PortraitInventory = "UI/Portraits/Inventory/Connor_inventory",
	PortraitLarge = "Mod/Pmb5Nio/Images/mod_Neelix_large.jpg",
	SkillInclinations = {
		Combat = "Interested",
		Cooking = "Interested",
		Farming = "Interested",
	},
	Skills = {
		Combat = 1,
		Cooking = 2,
		Farming = 2,
	},
	SkinColor = PlaceObj('ColorizationPropSet', {
		'EditableColor1', RGBA(176, 121, 43, 255),
		'EditableColor2', RGBA(254, 109, 75, 255),
		'EditableColor3', RGBA(255, 138, 92, 255),
	}),
	Teeth = "Teeth_Vicente",
	Traits = {
		"ExcquisiteCook",
		"Cheerful",
		"Glutton",
		"AvidFarmer",
		"Haggler",
		"Sickly",
		"Sleepy",
		"Attentive",
		"Calming",
		"InspirationalWriter",
	},
	Weight = 85000,
	anim_run = "standing_Walk_Run",
	anim_walk = "standing_Walk_Free2",
	comment = "Neelix",
	id = "Neelix",
	save_in = "Mod/Pmb5Nio",
}),
PlaceObj('ModItemCharacterDef', {
	Age = 39,
	Bio = T(895389756380, --[[ModItemCharacterDef Belanna Bio]] "B'Elanna Torres is a passionate and determined engineer celebrated for her exceptional technical skill, sharp problem-solving, and adaptability under pressure. With a deep understanding of starship systems and a relentless drive for innovation, she thrives in high-stakes situations where quick thinking is essential. Her resilience and creativity allow her to find effective solutions even in the most demanding conditions. Guided by her determination and commitment to excellence, Torres continually pushes the boundaries of engineering and proves herself an indispensable member of the crew."),
	Equipment = {
		"Armor_Shoes_Carbon",
		"Armor_Jacket_Carbon",
		"Armor_Pants_Carbon",
	},
	Eyes = "Eyes_Gabriele",
	FatiguePerDay = 55000,
	FavoriteFood = {
		"ChefsSteak",
	},
	FavoriteRelaxation = {
		"Drinking",
		"TargetPractice",
	},
	FirstName = T(946613322635, --[[ModItemCharacterDef Belanna FirstName]] "B'Elanna"),
	Hair = "HairFemale4",
	HairColor1 = 4278584581,
	HairColor2 = 4279176975,
	HairMetallic = -77,
	HairParam1 = 89,
	HairParam2 = 35,
	HairParam3 = 127,
	Head = "Head_Vanessa",
	Headline = T(357532908572, --[[ModItemCharacterDef Belanna Headline]] "Chief Engineer"),
	Height = 1640,
	IdealWeight = 65000,
	KnownTechs = {
		"MechCores",
		"SmallMech",
	},
	LastName = T(285399750892, --[[ModItemCharacterDef Belanna LastName]] "Torres"),
	Payment = 45000000,
	PerceivedGender = "Female",
	Portrait = "Mod/Pmb5Nio/Images/mod_BElanna_small.jpg",
	PortraitInventory = "UI/Portraits/Inventory/Vanessa_inventory",
	PortraitLarge = "Mod/Pmb5Nio/Images/mod_BElanna_large.jpg",
	SkillInclinations = {
		Combat = "Interested",
		Cooking = "Indifferent",
		Farming = "Indifferent",
		Healing = "Indifferent",
	},
	Skills = {
		Combat = 2,
		Construction = 1,
		Crafting = 1,
		Physical = 3,
	},
	SkinColor = PlaceObj('ColorizationPropSet', {
		'EditableColor1', RGBA(162, 97, 59, 255),
		'EditableColor2', RGBA(162, 107, 54, 255),
		'EditableColor3', RGBA(131, 69, 55, 255),
	}),
	Teeth = "Teeth_Gabriele",
	TemperatureHigh = 42000,
	TemperatureLow = 12000,
	Traits = {
		"Engineer",
		"CombatInstructor",
		"Bloodlust",
		"Glutton",
	},
	Weight = 65000,
	anim_idle2 = "standing_Idle_Free2_Female",
	anim_idle3 = "standing_Idle_Free3_Female",
	anim_idle4 = "standing_Idle_Free7_Female",
	anim_idle5 = "standing_Idle_Free_Sweat_Female",
	anim_idle6 = "standing_Idle_Free_CleanShoe_Female",
	anim_idle_happy10 = "standing_Idle_Free_CleanShoe_Female",
	anim_idle_happy2 = "standing_Idle_Free2_Female",
	anim_idle_happy3 = "standing_Idle_Free3_Female",
	anim_idle_happy4 = "standing_Idle_Free4_Female",
	anim_idle_happy5 = "standing_Idle_Free5_Female",
	anim_idle_happy6 = "standing_Idle_Free6_Female",
	anim_idle_happy7 = "standing_Idle_Free7_Female",
	anim_idle_happy8 = "standing_Idle_Free_Sweat_Female",
	anim_run = "standing_Walk_Run_Female",
	anim_walk = "standing_Walk_Free2_Female",
	anim_walk_distress = "standing_Walk_Distress_Female",
	anim_walk_haste = "standing_Walk_Haste_Female",
	comment = "B'Elanna Torres",
	id = "Belanna",
	save_in = "Mod/Pmb5Nio",
}),
PlaceObj('ModItemCharacterDef', {
	Age = 44,
	Bio = T(128869147344, --[[ModItemCharacterDef Doctor Bio]] "The Doctor is a holographic medical program brought to life with a growing sense of personality and curiosity. Designed to care for the crew, he excels at diagnosing and treating injuries and illnesses with precision and skill. Over time, he has developed his own perspective, often showing humor, determination, and a desire to learn about people.\n\nThough initially limited by his programming, he adapts quickly, finding creative solutions to challenges and expanding his knowledge beyond medicine. His dedication, intelligence, and growing empathy make him a reliable and resourceful member of any team."),
	Equipment = {
		"Shirt_Heavy_Good",
		"Pants_Spaceship",
		"Jacket_Spaceship",
		"Shoes_Light",
	},
	FavoriteFood = {
		"SweetSyrup",
	},
	FavoriteRelaxation = {
		"PlayingMusic",
		"Reading",
	},
	FirstName = T(362674360102, --[[ModItemCharacterDef Doctor FirstName]] "Doctor"),
	ForbiddenBreakdowns = {
		"Berserk",
		"FoodBinge",
		"DrinkingBinge",
		"Initial_Crying",
	},
	Gender = "Male",
	Hair = "Hair_Carter",
	HairColor1 = 4281670934,
	HairColor2 = 4279702547,
	HairParam3 = 127,
	Head = "Head_Zander",
	Headline = T(384435125152, --[[ModItemCharacterDef Doctor Headline]] "Emergency Medical Hologram"),
	Height = 1900,
	IdealWeight = 75000,
	LastName = "",
	Payment = 45000000,
	PerceivedGender = "Male",
	Portrait = "Mod/Pmb5Nio/Images/mod_Doctor_small.jpg",
	PortraitInventory = "UI/Portraits/Inventory/Zander_inventory",
	PortraitLarge = "Mod/Pmb5Nio/Images/mod_Doctor_large.jpg",
	SkillInclinations = {
		Combat = "Indifferent",
		Cooking = "Indifferent",
		Healing = "Interested",
		Intellectual = "Interested",
	},
	Skills = {
		Healing = 6,
		Intellectual = 4,
	},
	SkinColor = PlaceObj('ColorizationPropSet', {
		'EditableColor1', RGBA(255, 132, 94, 255),
		'EditableColor2', RGBA(254, 109, 75, 255),
		'EditableColor3', RGBA(176, 125, 100, 255),
	}),
	Traits = {
		"NightOwl",
		"Gloomy",
		"ImpeccableHealer",
		"Pacifist",
		"MusicalProdigy",
		"Genius",
		"Inedia",
		"Intimidating",
		"InspirationalWriter",
		"Agoraphobia",
	},
	Weight = 75000,
	anim_run = "standing_Walk_Run",
	comment = "The Doctor",
	id = "Doctor",
	save_in = "Mod/Pmb5Nio",
}),
PlaceObj('ModItemCharacterDef', {
	Age = 36,
	Bio = T(880624393891, --[[ModItemCharacterDef Seven Bio]] "Seven of Nine is a disciplined and analytical former Borg known for her exceptional intellect, rapid learning, and technical precision. Her ability to master complex systems and develop innovative solutions makes her indispensable in any mission requiring efficiency and strategy. Guided by logic yet driven by an emerging sense of individuality, she continually seeks to understand and reclaim her humanity. This balance between machine-like focus and human curiosity defines her as both a formidable specialist and a compelling figure of personal growth."),
	Equipment = {
		"Shirt_Heavy_Good",
		"Shoes_Normal",
		"Pants_Light_Good",
		"Jacket_Spaceship",
	},
	Eyes = "Eyes_Larisa",
	FirstName = T(830417876283, --[[ModItemCharacterDef Seven FirstName]] "Seven"),
	ForbiddenBreakdowns = {
		"Stealing",
		"FoodBinge",
		"DrinkingBinge",
	},
	Hair = "Hair_Larisa",
	HairColor1 = 4289030938,
	HairColor2 = 4282128642,
	HairMetallic = -85,
	HairParam8 = 383,
	HairRoughness = 21,
	Head = "Head_Laara",
	Headline = T(915355420145, --[[ModItemCharacterDef Seven Headline]] "Rescued from the Borg"),
	Height = 1720,
	IdealWeight = 55000,
	LastName = "",
	NickName = T(663974180672, --[[ModItemCharacterDef Seven NickName]] "Seven of Nine"),
	Payment = 90000000,
	PerceivedGender = "Female",
	Portrait = "Mod/Pmb5Nio/Images/mod_Seven_small.jpg",
	PortraitInventory = "UI/Portraits/Inventory/Laara_inventory",
	PortraitLarge = "Mod/Pmb5Nio/Images/mod_Seven_large.jpg",
	SkillInclinations = {
		Intellectual = "Interested",
	},
	Skills = {
		Combat = 2,
		Intellectual = 5,
		Physical = 1,
	},
	SkinColor = PlaceObj('ColorizationPropSet', {
		'EditableColor1', RGBA(255, 159, 116, 255),
		'EditableColor2', RGBA(255, 86, 58, 255),
		'EditableColor3', RGBA(60, 10, 2, 255),
	}),
	Teeth = "Teeth_Larisa",
	Traits = {
		"Inedia",
		"Genius",
		"Healthy",
		"QuickSleeper",
		"Intimidating",
	},
	Weight = 55000,
	anim_idle2 = "standing_Idle_Free2_Female",
	anim_idle3 = "standing_Idle_Free3_Female",
	anim_idle4 = "standing_Idle_Free7_Female",
	anim_idle5 = "standing_Idle_Free_Sweat_Female",
	anim_idle6 = "standing_Idle_Free_CleanShoe_Female",
	anim_idle_happy10 = "standing_Idle_Free_CleanShoe_Female",
	anim_idle_happy2 = "standing_Idle_Free2_Female",
	anim_idle_happy3 = "standing_Idle_Free3_Female",
	anim_idle_happy4 = "standing_Idle_Free4_Female",
	anim_idle_happy5 = "standing_Idle_Free5_Female",
	anim_idle_happy6 = "standing_Idle_Free6_Female",
	anim_idle_happy7 = "standing_Idle_Free7_Female",
	anim_idle_happy8 = "standing_Idle_Free_Sweat_Female",
	anim_run = "standing_Walk_Run_Female",
	anim_walk = "standing_Walk_Free_Female",
	anim_walk_distress = "standing_Walk_Distress_Female",
	anim_walk_haste = "standing_Walk_Haste_Female",
	comment = "Seven of Nine",
	id = "Seven",
	save_in = "Mod/Pmb5Nio",
}),
PlaceObj('ModItemCharacterDef', {
	Age = 17,
	Bio = T(830150262595, --[[ModItemCharacterDef Kes Bio]] "Kes is a gentle and curious young woman who approaches every experience with gratitude and wonder. Though her life span is short, she learns quickly and finds joy in discovery. Intelligent and empathetic, she has a natural gift for understanding others and easing tension within a group.\n\nRaised in an underground settlement, Kes always longed to explore and learn. Her calm strength and compassion make her a steady presence in difficult times, and her curiosity drives her to master new skills wherever she goes."),
	Equipment = {
		"Shoes_Normal",
		"Shirt_Light_Crude",
		"Pants_Light_Good",
		"Jacket_Light_Good",
	},
	Eyes = "Eyes_Krista",
	FavoriteFood = {
		"Cake",
	},
	FavoriteRelaxation = {
		"PleasureWalk",
		"SnowmanMaking",
		"Reading",
	},
	FirstName = T(133393162206, --[[ModItemCharacterDef Kes FirstName]] "Kes"),
	ForbiddenBreakdowns = {
		"Bullying",
		"DrinkingBinge",
	},
	Hair = "HairFemale2",
	HairColor1 = 4293581137,
	HairColor2 = 4282927401,
	HairMetallic = -70,
	HairParam2 = 22,
	HairParam3 = 127,
	HairParam7 = 161,
	HairParam8 = 383,
	HairRoughness = 27,
	Head = "Head_Samanta",
	Headline = T(383296904388, --[[ModItemCharacterDef Kes Headline]] "Ocampa"),
	Height = 1500,
	IdealWeight = 46000,
	LastName = "",
	Payment = 75000000,
	PerceivedGender = "Female",
	Portrait = "Mod/Pmb5Nio/Images/mod_Kes_small.jpg",
	PortraitInventory = "UI/Portraits/Inventory/Krista_inventory",
	PortraitLarge = "Mod/Pmb5Nio/Images/mod_Kes_large.jpg",
	SkillInclinations = {
		Farming = "Interested",
		Healing = "Interested",
	},
	Skills = {
		Farming = 1,
		Healing = 1,
		Intellectual = 1,
	},
	SkinColor = PlaceObj('ColorizationPropSet', {
		'EditableColor1', RGBA(255, 148, 101, 255),
		'EditableColor2', RGBA(255, 78, 54, 255),
		'EditableColor3', RGBA(245, 180, 145, 255),
	}),
	Teeth = "Teeth_Krista",
	Traits = {
		"Calming",
		"Attentive",
		"AvidFarmer",
		"Pacifist",
		"Neurotic",
	},
	Weight = 46000,
	anim_idle2 = "standing_Idle_Free2_Female",
	anim_idle3 = "standing_Idle_Free3_Female",
	anim_idle4 = "standing_Idle_Free7_Female",
	anim_idle5 = "standing_Idle_Free_Sweat_Female",
	anim_idle6 = "standing_Idle_Free_CleanShoe_Female",
	anim_idle_happy10 = "standing_Idle_Free_CleanShoe_Female",
	anim_idle_happy2 = "standing_Idle_Free2_Female",
	anim_idle_happy3 = "standing_Idle_Free3_Female",
	anim_idle_happy4 = "standing_Idle_Free4_Female",
	anim_idle_happy5 = "standing_Idle_Free5_Female",
	anim_idle_happy6 = "standing_Idle_Free6_Female",
	anim_idle_happy7 = "standing_Idle_Free7_Female",
	anim_idle_happy8 = "standing_Idle_Free_Sweat_Female",
	anim_run = "standing_Walk_Run_Female",
	anim_walk = "standing_Walk_Free_Female",
	anim_walk_distress = "standing_Walk_Distress_Female",
	anim_walk_haste = "standing_Walk_Haste_Female",
	comment = "Kes",
	id = "Kes",
	save_in = "Mod/Pmb5Nio",
}),
}
