return PlaceObj('ModDef', {
	'title', "Voyager Crew",
	'description', "This mod adds characters from Star Trek: Voyager.\nOnly characters, no gameplay changes.",
	'image', "Mod/Pmb5Nio/Images/star-trek-voyager.jpg",
	'last_changes', "fix skills",
	'id', "Pmb5Nio",
	'author', "oivlisLhog",
	'version', 128,
	'lua_revision', 233360,
	'saved_with_revision', 373414,
	'has_data', true,
	'saved', 1758795145,
	'steam_id', "3573518914",
	'TagCharacters', true,
})